local M = {}
M.theme = {
  fg = "#c5c5c5",
  fg2 = "#6b6b6b",
  bg = "#292929",
  bg2 = "#151515",
  blue = "#658db6",
  cyan = "#77b4b3",
  green = "#7ab690",
  olive = "#adae7d",
  orange = "#c9a175",
  purple = "#9d65af",
  red = "#da7890",
}
M.vi_mode = {
  ["n"] = M.theme.fg,
  ["niI"] = M.theme.green,
  ["niR"] = M.theme.red,
  ["niV"] = M.theme.red,
  ["no"] = M.theme.fg,
  ["nov"] = M.theme.fg,
  ["noV"] = M.theme.fg,
  ["no"] = M.theme.fg,
  ["i"] = M.theme.green,
  ["ic"] = M.theme.green,
  ["ix"] = M.theme.green,
  ["s"] = M.theme.red,
  ["S"] = M.theme.red,
  ["R"] = M.theme.red,
  ["Rv"] = M.theme.red,
  ["v"] = M.theme.purple,
  ["V"] = M.theme.purple,
  [""] = M.theme.purple,
  ["vs"] = M.theme.purple,
  ["Vs"] = M.theme.purple,
  ["s"] = M.theme.purple,
  ["r"] = M.theme.cyan,
  ["r?"] = M.theme.cyan,
  ["c"] = M.theme.cyan,
  ["t"] = M.theme.cyan,
}
M.vi_mode2 = {
  ["n"] = { name = "StalineNormal", fg = M.theme.fg },
  ["niI"] = { name = "StalineInsert", fg = M.theme.green },
  ["niR"] = { name = "StalineReplace", fg = M.theme.red },
  ["niV"] = { name = "StalineReplace", fg = M.theme.red },
  ["no"] = { name = "StalineNormal", fg = M.theme.fg },
  ["nov"] = { name = "StalineNormal", fg = M.theme.fg },
  ["noV"] = { name = "StalineNormal", fg = M.theme.fg },
  ["no"] = { name = "StalineNormal", fg = M.theme.fg },
  ["i"] = { name = "StalineInsert", fg = M.theme.green },
  ["ic"] = { name = "StalineInsert", fg = M.theme.green },
  ["ix"] = { name = "StalineInsert", fg = M.theme.green },
  ["s"] = { name = "StalineReplace", fg = M.theme.red },
  ["S"] = { name = "StalineReplace", fg = M.theme.red },
  ["R"] = { name = "StalineReplace", fg = M.theme.red },
  ["Rv"] = { name = "StalineReplace", fg = M.theme.red },
  ["v"] = { name = "StalineVisual", fg = M.theme.purple },
  ["V"] = { name = "StalineVisual", fg = M.theme.purple },
  [""] = { name = "StalineVisual", fg = M.theme.purple },
  ["vs"] = { name = "StalineVisual", fg = M.theme.purple },
  ["Vs"] = { name = "StalineVisual", fg = M.theme.purple },
  ["s"] = { name = "StalineVisual", fg = M.theme.purple },
  ["?"] = { name = "StalineSearch", fg = M.theme.orange },
  ["r"] = { name = "StalineCommand", fg = M.theme.cyan },
  ["r?"] = { name = "StalineCommand", fg = M.theme.cyan },
  ["c"] = { name = "StalineCommand", fg = M.theme.cyan },
  ["t"] = { name = "StalineCommand", fg = M.theme.cyan },
  ["!"] = { name = "StalineCommand", fg = M.theme.cyan },
}
return M
